const API_CALLS = {
  SaveProfile: {
    api: 'saveProfile',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  GetProfile: {
    api: 'getProfile',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetAllCompetitions: {
    api: 'getCompetitions',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetFtpCompetitions: {
    api: 'getCompetitions',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetCompetitionsActivities: {
    api: 'getCompetitionActivities',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetCompetitionsFriends: {
    api: 'getFriends',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetCompetitionsFriendsBlocking: {
    api: 'getFriends',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetCompetitionsLeaderboard: {
    api: 'getLeaderboard',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetCompetitionsRewards: {
    api: 'getRewards',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  StartChallenge: {
    api: 'startChallenge',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  PlayChallenge: {
    api: 'playChallenge',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  SaveChallenge: {
    api: 'saveChallenge',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  SetInvitationStatus: {
    api: 'setInvitationStatus',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  SearchUser: {
    api: 'searchUsers',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  ClaimReward: {
    api: 'claimReward',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  GetOpponents: {
    api: 'getFriends',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  SendMessage: {
    api: 'sendMessage',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetMessage: {
    api: 'getMessages',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetStats: {
    api: 'getStats',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetProfileForClaim: {
    api: 'getProfile',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  GetMessageLowPriority: {
    api: 'getMessages',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 0,
  },
  GetCompetitionsActivitiesLowPriority: {
    api: 'getCompetitionActivities',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 0,
  },
  GetCompetitionsBlocking: {
    api: 'getCompetitionActivities',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: false,
    from: 0,
    priority: 0,
  },
  ChangeGrade: {
    api: 'changeGrade',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  SocialLogin: {
    api: 'socialLogin',
    isAuthenticationReq: false,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  BlockFriend: {
    api: 'blockfriend',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: true,
    from: 0,
    priority: 1,
  },
  SetGradeAndPoints: {
    api: 'setGradeAndPoints',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetRewardsHistory: {
    api: 'getRewardTransactions',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetRecommendationsBlocking: {
    api: 'getRecommendations',
    isAuthenticationReq: true,
    setSpinner: true,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  GetRecommendations: {
    api: 'getRecommendations',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
  AddSecretCode: {
    api: 'addSecretCode',
    isAuthenticationReq: true,
    setSpinner: false,
    setCancelBtn: false,
    from: 0,
    priority: 1,
  },
};

export default API_CALLS;
