const LIMITS_CONFIG = {
  PASSWORD_MIN_LENGTH: 5,
  PASSWORD_MAX_LENGTH: 50,
  SEARCH_MIN_REQ: 3,
  SEARCH_BOUNCE_TIME: 300,
  CNIC_LENGTH: 14,
  PHONE_NO_LENGTH: 11,
  FULL_NAME_MIN: 3,
  REWARD_UPLOAD_IMAGE_SIZE: 500000,
  SECRET_CODE: 3,
};

const KP_SUPPORTED_OS = {
  ANDROID: 'android',
  IOS: 'ios',
  WEB: 'web',
  MOBILE_WEB: 'mobile_web',
};

export { LIMITS_CONFIG, KP_SUPPORTED_OS };
